Game system
arkavidia-hmif/itfest-backend pull request #11
Opened 2021-01-19 09:59 UTC by ilhamsyahids

2021-01-19 12:49 UTC, jrandiny requested changes

2021-01-19 12:49 UTC, jrandiny commented on src/controller/GameOldController.ts
> +    delete game.tenant;
Kl gak mau, kenapa diawal dijoin?

2021-01-19 12:49 UTC, jrandiny commented on src/controller/GlobalScoreboardController.ts
> +            var limit: number = 1000; //dafault
jangan pake var

2021-01-19 12:49 UTC, jrandiny commented on src/controller/GlobalScoreboardController.ts
> +            if(req.query.limit !== undefined){
Ini bisa pake yg `||`

2021-01-19 12:49 UTC, jrandiny commented on src/controller/InventoryController.ts
> +    if (response.locals.auth.role !== UserRole.ADMIN && item.owner !== response.locals.auth.id) {
ini dah dites kan ya tipenya beneran sama?

2021-01-19 12:49 UTC, jrandiny commented on src/controller/ScoreboardController.ts
> +            console.log(req.query)
jangan console.log

2021-01-19 12:49 UTC, jrandiny commented on src/controller/ScoreboardController.ts
> +            const gameId: any = +req.params.id;
Jangan any kl bisa

2021-01-19 12:49 UTC, jrandiny commented on src/entity/GameState.ts
> +  // @CreateDateColumn()
Kenapa gak pake createdatecolumn?

2021-01-19 12:49 UTC, jrandiny commented on src/entity/Shop.ts
> +    @Column({type: "timestamp", default: () => "CURRENT_TIMESTAMP"})
Kenapa gak pake createdatecolumn

2021-01-19 14:14 UTC, jrandiny commented
Sama btw jangan lupa direbase ke master

2021-01-20 09:51 UTC, ilhamsyahids commented on src/controller/GameOldController.ts
> +    delete game.tenant;
Controller ini ga di pake, game controller sebelumnya

2021-01-20 16:47 UTC, jrandiny requested changes

2021-01-20 16:47 UTC, jrandiny commented on src/entity/GameState.ts
> +  @CreateDateColumn()
Kalau submit time dan start time sama, untuk apa?

2021-01-20 16:47 UTC, jrandiny commented on src/controller/GlobalScoreboardController.ts
> +            let limit: number = +req.query.limit || 1000; //dafault
Biasain pake const aja, lebih mudah untuk cek correctnessnya kalau pake const

2021-01-20 16:47 UTC, jrandiny commented on src/controller/ScoreboardController.ts
> +    //                                 userId : authData.id
Di delete aja jangan dicomment kl gak dipake lagi, kalau balikin bisa pake git punya sistem

2021-01-20 16:47 UTC, jrandiny commented on src/entity/Shop.ts
> +    @Column({type: "timestamp", default: () => "CURRENT_TIMESTAMP"})
Ini kenapa gak pake createdatecolumn?

2021-01-23 02:38 UTC, ilhamsyahids commented on src/entity/GameState.ts
> +  @CreateDateColumn()
cc: @primayoriko

2021-01-23 04:34 UTC, primayoriko commented on src/entity/GameState.ts
> +  @CreateDateColumn()
oh itu seinget saya dlu kalau misal satu game bisa dimainin berkali2, buat nolak kalau game sebelumnya dimaininnya baru bentar, buat ngehindarin brute force posting result.

2021-01-23 06:34 UTC, jrandiny commented on src/entity/GameState.ts
> +  @CreateDateColumn()
Dah aku fix

2021-01-23 06:35 UTC, jrandiny approved these changes

2021-01-23 06:37 UTC, merged