Fixing game
arkavidia-hmif/itfest-backend pull request #15
Opened 2021-01-25 01:39 UTC by primayoriko

benerin beberapa error di game controller + model, sama ngebenerin seed yang gabisa jalan. 
NOTE: tadi di coba di mysql bisa, tapi di postgre entah kenapa gabisa.

2021-01-25 02:38 UTC, jrandiny requested changes

2021-01-25 02:38 UTC, jrandiny commented on .gitignore
> +ormconfig.js
Eh? kenapa

2021-01-25 02:38 UTC, jrandiny commented on ormconfig.js
> +  return {
Kenapa ini masuk?

2021-01-25 02:38 UTC, jrandiny commented on package.json
> +    "mysql": "^2.18.1",
Mysql sengaja diapus, soalnya ada beda sm postgres

2021-01-25 02:38 UTC, jrandiny commented on src/controller/GameController.ts
> +        // const visitor = await tmVisitorRepository.findOne(userId, { relations: ["userId"] });
Comment diapus aja

2021-01-25 02:38 UTC, jrandiny commented on src/seed/tenant.ts
> +    x: 1,
Ini gak jadi ada x y kan

2021-01-25 02:38 UTC, jrandiny commented on src/seed/user.ts
> +    // id: 1
Kenapa?

2021-01-25 02:38 UTC, jrandiny commented on src/entity/GlobalScoreboard.ts
> +  @OneToOne((type) => User, { primary: true })
Ini dah dites?

2021-01-25 02:38 UTC, jrandiny commented
Btw kita pakenya postgres di server

2021-01-25 10:40 UTC, primayoriko commented on .gitignore
> +ormconfig.js
supaya tidak masuk kak config orm saya tadi

2021-01-25 10:41 UTC, primayoriko commented on ormconfig.js
> +  return {
nah tadi seinget saya sudah di .gitignore, knp ya

2021-01-25 10:41 UTC, primayoriko commented on package.json
> +    "mysql": "^2.18.1",
tadi saya cek dengan postgres ada kendala, jadi testing make mysql

2021-01-25 10:42 UTC, primayoriko commented on src/seed/tenant.ts
> +    x: 1,
oh bener kak gaada? kalau gitu seperti nya ada yg perlu di rollback

2021-01-25 10:44 UTC, primayoriko commented on src/seed/user.ts
> +    // id: 1
kan id primary generated ya, klo di postgres dia serial jadi aneh gitu seinget saya klo misal di assign ID nya, cm itu kalau pake orm lain sih, takutnya di type orm juga sama

2021-01-25 10:44 UTC, primayoriko commented on src/entity/GlobalScoreboard.ts
> +  @OneToOne((type) => User, { primary: true })
tadi sudah sih kak

2021-01-25 10:45 UTC, primayoriko commented on src/controller/GameController.ts
> +        // const visitor = await tmVisitorRepository.findOne(userId, { relations: ["userId"] });
ok

2021-02-02 04:22 UTC, jrandiny commented
Fail lintnya

2021-02-04 11:39 UTC, jrandiny commented
Masih konflik sm master

2021-02-05 17:00 UTC, jrandiny approved these changes

2021-02-05 17:01 UTC, merged