Add field to visitor
arkavidia-hmif/itfest-backend pull request #16
Opened 2021-01-25 06:09 UTC by ilhamsyahids

2021-01-25 12:58 UTC, jrandiny requested changes

2021-01-25 12:58 UTC, jrandiny commented on src/routes/user.ts
> +  const telpCheck = () => check("telp").isString().withMessage("must be a string");
Tolong tambah cek panjang telponnya

2021-01-25 12:58 UTC, jrandiny commented on src/routes/user.ts
> +  const photoCheck = () => check("photo").isString().withMessage("must be a string");
Eh photo untuk apa?

2021-01-25 17:53 UTC, ilhamsyahids commented on src/routes/user.ts
> +  const photoCheck = () => check("photo").isString().withMessage("must be a string");
foto profile?

2021-01-26 04:19 UTC, jrandiny commented on src/routes/user.ts
> +  const photoCheck = () => check("photo").isString().withMessage("must be a string");
Emang ada?

2021-01-26 04:30 UTC, ilhamsyahids commented on src/routes/user.ts
> +  const photoCheck = () => check("photo").isString().withMessage("must be a string");
Kemaren bilang yg kurang itu
-profile
-telp
-institusi

Profile ini maksudnya apa?

2021-01-26 07:28 UTC, jrandiny commented on src/routes/user.ts
> +  const photoCheck = () => check("photo").isString().withMessage("must be a string");
Profile itu maksudnya di bagian profile, kurang dua itu

2021-01-26 07:43 UTC, jrandiny approved these changes

2021-01-26 07:43 UTC, merged