add reset password feature
arkavidia-hmif/itfest-backend pull request #18
Opened 2021-01-28 14:11 UTC by primayoriko

Nambah fitur buat reset pass, sisanya gaada yang diganti.

2021-01-28 15:44 UTC, jrandiny commented
Reset passwordnya kirim email

2021-01-28 15:45 UTC, jrandiny requested changes

2021-01-28 15:45 UTC, jrandiny commented on src/controller/UserController.ts
> +  async resetPassword(request: Request, response: Response){
Request reset passwordnya sistem yg kirim ke email dst

2021-01-29 00:00 UTC, primayoriko commented on src/controller/UserController.ts
> +  async resetPassword(request: Request, response: Response){
maksud kak? flow nya jadi nya gmn tuh?

2021-02-01 02:30 UTC, jrandiny requested changes

2021-02-01 02:30 UTC, jrandiny commented on src/controller/UserController.ts
> +      const token: String = request.params.token;
string, s nya kecil, yang besar itu kelas bukan type

2021-02-01 02:30 UTC, jrandiny commented on src/controller/UserController.ts
> +        if(verification.type == VerificationType.CONFIRM_EMAIL){
Ini === aja kalau bisa

2021-02-01 02:30 UTC, jrandiny commented on src/controller/UserController.ts
> +        } else if (password !== "") {
kenapa elsenya bukan verification type lain?

2021-02-01 02:30 UTC, jrandiny commented on src/routes/user.ts
> +  router.post("/validation/:token([0-9a-zA-Z]+)", [
Gak ada cek bodynya?

2021-02-01 02:30 UTC, jrandiny commented
Sama jangan lupa rebase dari master

2021-02-04 11:35 UTC, jrandiny approved these changes

2021-02-04 11:35 UTC, merged